### ISSUE TITLE
Set Fixed Size On Popup Tool Windows

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Brett-Tech-Control-Panel#1]
Some of the tools such as the **Process Manager** or the **System Info** that pop up are re-sizable and even have full-screen capabilities. However, the forms and graphics/buttons themselves do not adjust to the window sizing, which makes having re-sizable windows kind of useless.

**Comment by hudson1740** [comment]
fixed

**Comment by MattMoradi** [comment]
The full screen option is still available on the **System Information** tool. Also, the resize option is still available for shrinking the window. This should probably be disabled as well.

**Comment by hudson1740** [comment]
fixed for next push

**Comment by MattMoradi** [comment]
Fixes look good. However, it'd be nice if we could find a way to stop the resizing double arrows at the edge of the window from popping up. The main window form doesn't have this issue, so it must be possible for the popup forms as well. Perhaps if it hasn't been done already, we could try setting the re-sizable option to **false** or something like that.

**Comment by MattMoradi** [comment]
Also the resizing issue still exists on the virus scanner.

**Comment by hudson1740** [comment]
fixed
