### ISSUE TITLE
IP_Tester Improvements

### ISSUE THREAD

**Issue by MattMoradi** [Brett-Tech-Networking/Brett-Tech-Control-Panel#3]
The hover function for the refresh button on the IP_Tester should probably say something like Refresh, not ToolStripButton1. Also, for the title window, we probably shouldn't include an underscore, as it's not really necessary for a title. It's good for file and variable names though. 

![image](https://user-images.githubusercontent.com/14935352/36226878-ff18646e-1183-11e8-8a0e-68fff1bc54be.png)

**Comment by hudson1740** [comment]
fixed for next push

**Comment by matthew17754** [comment]
Fixes look good. However, it'd be nice if we could find a way to stop the resizing arrows at the edge of the window from popping up. The main window form doesn't have this issue, so it must be possible for the popup forms as well. Perhaps if it hasn't been done already, we could try setting the re-sizable option to **false** or something like that.
